### ISSUE TITLE
请求会返回握手失败

### ISSUE THREAD

**Issue by yb1959080058** [c-ttpfx/chatgpt-java-wx#16]
请输入问题(q退出)：你好
failed
javax.net.ssl.SSLHandshakeException: TLS handshake failed
	at org.apache.hc.core5.reactor.ssl.SSLIOSession.updateEventMask(SSLIOSession.java:454)
	at org.apache.hc.core5.reactor.ssl.SSLIOSession.setEvent(SSLIOSession.java:802)
	at org.apache.hc.core5.reactor.InternalDataChannel.setEvent(InternalDataChannel.java:359)
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1StreamDuplexer.requestShutdown(AbstractHttp1StreamDuplexer.java:424)
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1StreamDuplexer.onInput(AbstractHttp1StreamDuplexer.java:348)
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1IOEventHandler.inputReady(AbstractHttp1IOEventHandler.java:64)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1IOEventHandler.inputReady(ClientHttp1IOEventHandler.java:41)
	at org.apache.hc.core5.reactor.ssl.SSLIOSession.decryptData(SSLIOSession.java:624)
	at org.apache.hc.core5.reactor.ssl.SSLIOSession.access$200(SSLIOSession.java:74)
	at org.apache.hc.core5.reactor.ssl.SSLIOSession$1.inputReady(SSLIOSession.java:202)
	at org.apache.hc.core5.reactor.InternalDataChannel.onIOEvent(InternalDataChannel.java:142)
	at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:51)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.processEvents(SingleCoreIOReactor.java:178)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:127)
	at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:86)
	at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by c-ttpfx** [comment]
![image](https://github.com/c-ttpfx/chatgpt-java-wx/assets/101882388/db8dea0e-5790-4043-9364-d75748ba45a3)

在README里面有说

**Comment by yb1959080058** [comment]
![image](https://github.com/c-ttpfx/chatgpt-java-wx/assets/28618039/a1d21048-cb02-4010-a42d-59bd6482e277)
我使用了也是351版本，不懂为啥还是会出现这个错误

**Comment by yb1959080058** [comment]
本地另一个vpn问题
